- name: install NGINX and run
  hosts: all
  become: yes # sudo access
  serial: 2
  tasks:
  - name: install NGINX
    ansible.builtin.package:
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes